browser: chrome
headless: false
window_size: "1920,1080"

accept_insecure_certs: true
arguments:
  - "--ignore-certificate-errors"
  - "--allow-insecure-localhost"
  - "--no-sandbox"
  - "--disable-dev-shm-usage"
  - "--disable-gpu"
